import os
from os import *
TitleZero=('title Hello7L')
os.system(TitleZero)
os.system("color 01")
os.system("mode con: cols=55 lines=11")
cls = 'cls'
os.system(cls)
print("I Know What Year it is:")
a=float(raw_input("What Year Does it Say? : "))
b=float(raw_input("What Year Were You Born? : "))
d=float(raw_input("What Month Is It? Choose : "))
c=(a-b)
Day=("Your Age Is: ")
BirthDay=("100_year's_Birthday_at: ")
Years=("100_YEARS_LEFT: ")
e=(100+b)
f=(12-d)
g=(100-c)
#Print-Math--------------------------------------
print(Day)
print(c)
print(BirthDay)
print(e)
print(Years)
input(g)
